steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - gcf2
  - --source=.
  - --trigger-bucket=${_BUCKET_IMAGES_SCALED}
  - --set-env-vars=BUCKET_IMAGES_SCALED=${_BUCKET_IMAGES_SCALED},PROJECT_ID=$PROJECT_ID,TOPIC_NAME=${_TOPIC_EMAILS_TO_SEND}
  - --runtime=python37
